// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TwoFactorAuthentication1.Models;

public partial class Organizations
{
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string Issuer { get; set; }
}