// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TwoFactorAuthentication1.Models;

public partial class Verifications
{
    public int Id { get; set; }

    public string EmailAddress { get; set; }

    public string Secret { get; set; }

    public string Code { get; set; }

    public DateTime CreatedDate { get; set; }

    public TimeSpan CreatedTime { get; set; }
}