// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using RadioButtonsExample.Data.Configurations;
using RadioButtonsExample.Models;
using System;
using System.Collections.Generic;
#nullable disable

namespace RadioButtonsExample.Data;

public partial class Context : DbContext
{
    //public Context()
    //{
    //}

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Categories> Categories { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.CategoriesConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
