// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NotesRazorApp.Models;

namespace NotesRazorApp.Data.Configurations;

public partial class NoteConfiguration : IEntityTypeConfiguration<Note>
{
    public void Configure(EntityTypeBuilder<Note> entity)
    {

        // KP AutoInclude should be used with care
        // https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager
        //entity.Navigation(n => n.Category).AutoInclude();

        entity.HasIndex(e => e.CategoryId, "IX_Note_CategoryId");

        entity.HasOne(d => d.Category)
            .WithMany(p => p.Note)
            .HasForeignKey(d => d.CategoryId)
            .HasConstraintName("FK_Note_Category");

        entity.Property(x => x.DueDate).HasDefaultValueSql("getdate()");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Note> entity);
}

