// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Revenue.Configuration.Core1.Models;

public partial class AzureSettings
{
    public int Id { get; set; }

    public string Tenant { get; set; }

    public string TenantName { get; set; }

    public string TenantId { get; set; }

    public string Audience { get; set; }

    public string ClientId { get; set; }

    public string GraphClientId { get; set; }

    public string GraphClientSecret { get; set; }

    public string SignUpSignInPolicyId { get; set; }

    public string AzureGraphVersion { get; set; }

    public string MicrosoftGraphVersion { get; set; }

    public string AadInstance { get; set; }

    public bool? UseAdal { get; set; }

    public int? Identifier { get; set; }

    public virtual Applications IdentifierNavigation { get; set; }
}