// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Revenue.Configuration.Core1.Models;

public partial class GeneralSettings
{
    public int Id { get; set; }

    public string ServicePath { get; set; }

    public string ErrorMessageFromAddress { get; set; }

    public bool? ClientValidationEnabled { get; set; }

    public bool? UnobtrusiveJavaScriptEnabled { get; set; }

    public string MainDatabaseConnection { get; set; }

    public int? Identifier { get; set; }

    public virtual Applications IdentifierNavigation { get; set; }
}