// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Revenue.Configuration.Core1.Models;

public partial class MailSettings
{
    public int Id { get; set; }

    public string FromAddress { get; set; }

    public string Host { get; set; }

    public int? Port { get; set; }

    public int? TimeOut { get; set; }

    public string PickupFolder { get; set; }

    public string TestFromAddress { get; set; }

    public string RevenueCoordinator { get; set; }

    public int? Identifier { get; set; }

    public virtual Applications IdentifierNavigation { get; set; }
}