// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Revenue.Configuration.Core1.Models;

public partial class WebPageSettings
{
    public int Id { get; set; }

    public int VersionMajor { get; set; }

    public int VersionMinor { get; set; }

    public int VersionBuild { get; set; }

    public int VersionRevison { get; set; }

    public int? Identifier { get; set; }

    public string TheVersion { get; set; }

    public virtual Applications IdentifierNavigation { get; set; }
}