// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using EnvironmentApplication.Classes;

namespace WebApplication1.Models
{
    public partial class Taxpayer
    {
        public int Id { get; set; }

        [Display(Name = "First")]
        public string FirstName { get; set; }

        [Display(Name = "Last")]
        public string LastName { get; set; }


        [Display(Name = "SSN")]
        public string Ssn { get; set; }

        public string SocialMasked() => Ssn.MaskSsn();
        public string Pin { get; set; }

        [Display(Name = "Started")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? StartDate { get; set; }
        public int CategoryId { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? Added { get; set; }

        [Display(Name = "")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? DeletedOn { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? Modified { get; set; }
        public bool? Deleted { get; set; }

        public virtual Categories Category { get; set; }
    }
}