// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WebApplication1.Models;

namespace EnvironmentApplication.Data.Configurations;

public partial class TaxpayerConfiguration : IEntityTypeConfiguration<Taxpayer>
{
    public void Configure(EntityTypeBuilder<Taxpayer> entity)
    {
        entity.HasIndex(e => e.CategoryId, "IX_Taxpayer_CategoryId");

        entity.Property(e => e.Ssn).HasColumnName("SSN");

        entity.Property(e => e.StartDate).HasColumnType("date");

        entity.HasOne(d => d.Category)
            .WithMany(p => p.Taxpayer)
            .HasForeignKey(d => d.CategoryId);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Taxpayer> entity);
}