// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DropdownForCountries.Models;

public partial class Countries
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }
}