// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DropDownWithSelects.Models;

public partial class Categories
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int CategoryID { get; set; }

    /// <summary>
    /// Name
    /// </summary>
    public string CategoryName { get; set; }

    public override string ToString() => CategoryName;

}