// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DropDownWithSelects.Models;

public partial class ContactType
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int ContactTypeIdentifier { get; set; }

    /// <summary>
    /// Title
    /// </summary>
    public string ContactTitle { get; set; }

    public override string ToString() => ContactTitle;

}