// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Revenue.Configuration.Core1.Data.Configurations;
using Revenue.Configuration.Core1.Models;
using System;
using System.Collections.Generic;
#nullable disable

namespace Revenue.Configuration.Core1.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<AcedEmailSettings> AcedEmailSettings { get; set; }

    public virtual DbSet<Applications> Applications { get; set; }

    public virtual DbSet<AzureSettings> AzureSettings { get; set; }

    public virtual DbSet<GeneralSettings> GeneralSettings { get; set; }

    public virtual DbSet<MailSettings> MailSettings { get; set; }

    public virtual DbSet<WebPageSettings> WebPageSettings { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.AcedEmailSettingsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ApplicationsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AzureSettingsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.GeneralSettingsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MailSettingsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WebPageSettingsConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
