// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Revenue.Configuration.Core1.Data;
using Revenue.Configuration.Core1.Models;
using System;
using System.Collections.Generic;

namespace Revenue.Configuration.Core1.Data.Configurations
{
    public partial class WebPageSettingsConfiguration : IEntityTypeConfiguration<WebPageSettings>
    {
        public void Configure(EntityTypeBuilder<WebPageSettings> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_WebPageSettings1");

            entity.Property(e => e.TheVersion)
            .HasMaxLength(8000)
            .IsUnicode(false)
            .HasComputedColumnSql("((((((replace(str([VersionMajor]),' ','')+'.')+replace(str([VersionMinor]),' ',''))+'.')+replace(str([VersionBuild]),' ',''))+'.')+replace(str([VersionRevison]),' ',''))", false);

            entity.HasOne(d => d.IdentifierNavigation).WithMany(p => p.WebPageSettings)
            .HasForeignKey(d => d.Identifier)
            .HasConstraintName("FK_WebPageSettings_Applications");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WebPageSettings> entity);
    }
}
