// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TwoFactorAuthentication1.Data;
using TwoFactorAuthentication1.Models;

namespace TwoFactorAuthentication1.Data.Configurations
{
    public partial class OrganizationsConfiguration : IEntityTypeConfiguration<Organizations>
    {
        public void Configure(EntityTypeBuilder<Organizations> entity)
        {
            entity.Property(e => e.CompanyName).IsRequired();
            entity.Property(e => e.Issuer).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Organizations> entity);
    }
}
