// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TwoFactorAuthentication1.Data;
using TwoFactorAuthentication1.Models;

namespace TwoFactorAuthentication1.Data.Configurations
{
    public partial class VerificationsConfiguration : IEntityTypeConfiguration<Verifications>
    {
        public void Configure(EntityTypeBuilder<Verifications> entity)
        {
            entity.Property(e => e.Code).IsRequired();
            entity.Property(e => e.CreatedDate).HasColumnType("date");
            entity.Property(e => e.EmailAddress).IsRequired();
            entity.Property(e => e.Secret).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Verifications> entity);
    }
}
