// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NotesFormApp.Data;
using NotesFormApp.Models;
using System;
using System.Collections.Generic;

namespace NotesFormApp.Data.Configurations
{
    public partial class NoteConfiguration : IEntityTypeConfiguration<Note>
    {
        public void Configure(EntityTypeBuilder<Note> entity)
        {
            entity.HasOne(d => d.Category)
                .WithMany(p => p.Note)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Note_Category");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Note> entity);
    }
}
