// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DisplayAndEditorTemplatesApp.Models;

public partial class Address
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Street { get; set; }
    public string City { get; set; }

    public string State { get; set; }

    public string Zipcode { get; set; }
}