// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotesRazorApp.Models;

public partial class Category
{
    public Category()
    {
        Note = new HashSet<Note>();
    }

    public int CategoryId { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<Note> Note { get; set; }

    public override string ToString() => CategoryName;

}