// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;
using NotesRazorApp.Classes.Attributes;

namespace NotesRazorApp.Models;

public partial class Note
{
    public int NoteId { get; set; }

    [Display(Name = "Note")]
    [Required]
    [MinLength(6)]
    public string BodyText { get; set; }


    [GreaterThan("11/1/2022")]
    [Display(Name = "Due by")]
    [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy HH:mm tt}")]
    public DateTime? DueDate { get; set; }

    [Required]
    [Display(Name = "Done")]
    public bool Completed { get; set; }
    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }
}