// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NonFactorsGridStarter.Models;

namespace NonFactorsGridStarter.Data.Configurations;

public partial class Customers1Configuration : IEntityTypeConfiguration<Customers1>
{
    public void Configure(EntityTypeBuilder<Customers1> entity)
    {
        entity.Property(e => e.Country).IsRequired();
        entity.Property(e => e.FirstName).IsRequired();
        entity.Property(e => e.LastName).IsRequired();

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Customers1> entity);
}