// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Employees
{
    /// <summary>
    /// Id
    /// </summary>
    public int EmployeeId { get; set; }

    /// <summary>
    /// Last name
    /// </summary>
    public string LastName { get; set; }

    /// <summary>
    /// First name
    /// </summary>
    public string FirstName { get; set; }

    public int? ContactTypeIdentifier { get; set; }

    /// <summary>
    /// Title
    /// </summary>
    public string TitleOfCourtesy { get; set; }

    /// <summary>
    /// Birth date
    /// </summary>
    public DateTime? BirthDate { get; set; }

    /// <summary>
    /// Hiredate
    /// </summary>
    public DateTime? HireDate { get; set; }

    /// <summary>
    /// Street
    /// </summary>
    public string Address { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string PostalCode { get; set; }

    public int? CountryIdentifier { get; set; }

    /// <summary>
    /// Home phone
    /// </summary>
    public string HomePhone { get; set; }

    public string Extension { get; set; }

    public string Notes { get; set; }

    /// <summary>
    /// Manager
    /// </summary>
    public int? ReportsTo { get; set; }

    public virtual ContactType ContactTypeIdentifierNavigation { get; set; }

    public virtual Countries CountryIdentifierNavigation { get; set; }

    public virtual ICollection<Employees> InverseReportsToNavigation { get; } = new List<Employees>();

    public virtual ICollection<Orders> Orders { get; } = new List<Orders>();

    public virtual Employees ReportsToNavigation { get; set; }

    public virtual ICollection<Territories> Territory { get; } = new List<Territories>();
}