// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MockupApplication.Models;

public partial class UserLogin
{
    public int Id { get; set; }

    // for data protection
    [NotMapped]
    [BindProperty]
    public string EncryptedId { get; set; }

    [Display(Name = "Email")]
    public string EmailAddress { get; set; }

    [DataType(DataType.Text)]
    [MaxLength(5, ErrorMessage = "The {0} can not have more than {1} characters")]
    public string Pin { get; set; }
}