// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;

namespace FluentWebApplication.Models;

public partial class Person
{
    
    public int PersonId { get; set; }
    [Required]
    public  string FirstName { get; set; }
    [Required]
    public  string LastName { get; set; }
    [Required]
    public  string EmailAddress { get; set; }
}