// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotesFormApp.Models;

public partial class Note
{
    public int NoteId { get; set; }
    public string BodyText { get; set; }
    public DateTime? DueDate { get; set; }
    public bool? Completed { get; set; }
    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }
}