// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Revenue.Configuration.Core1.Models;

public partial class WebPageSettings
{
    public Version Version => new Version(VersionMajor, VersionMinor, VersionBuild, VersionRevison);
}